version: '3'
services:

  # https://github.com/mitre/fusera/wiki/FUSE-and-Docker
  python-fuse-sample:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./:/app"
      - "./srcpoint:/app/srcpoint"
    privileged: true
    cap_add: 
      - SYS_ADMIN
      - MKNOD
    devices:
      - "/dev/fuse:/dev/fuse"
